environment:
  PMTILES_URL: "${PMTILES_URL}"
packages:
  - name: protomaps
    functions:
      - name: tiles
        runtime: 'nodejs:18'
        limits:
          timeout: 5000
          memory: 256
